# 通用配置

project.name=sample-clean

server.port=8080

# spring 配置
spring.mvc.favicon.enabled=false
spring.web.resources.add-mappings=false

# clean 配置
#clean.log.enable=true
clean.log.patterns[0]=com.sample.clean.*.module.*
#clean.cqrs.enable=true
#clean.exception.handler.http.enable=true
#clean.extension.enable=true

# mybatis 配置
mybatis.check-config-location=false
mapper.useSimpleType=false

# 多数据源配置
spring.datasource.continue-on-error=true
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.stat-view-servlet.enabled=false
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false

# 数据源1
spring.datasource.primary.druid.name=primary
spring.datasource.primary.druid.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.primary.druid.url=jdbc:mysql://localhost:3308/cleandb?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.primary.druid.username=admin
spring.datasource.primary.druid.password=admin
spring.datasource.primary.druid.filter.stat.log-slow-sql=true
spring.datasource.primary.druid.filter.stat.slow-sql-millis=1000
spring.datasource.primary.druid.min-evictable-idle-time-millis=300000
spring.datasource.primary.druid.filter.stat.merge-sql=false
spring.datasource.primary.druid.initial-size=10
spring.datasource.primary.druid.min-idle=10
spring.datasource.primary.druid.max-wait=60000
spring.datasource.primary.druid.pool-prepared-statements=true
spring.datasource.primary.druid.test-while-idle=true
spring.datasource.primary.druid.validation-query=select 1
spring.datasource.primary.druid.filter.wall.config.multi-statement-allow=true
spring.datasource.primary.druid.time-between-eviction-runs-millis=60000
spring.datasource.primary.druid.max-pool-prepared-statement-per-connection-size=20
spring.datasource.primary.druid.max-active=100